apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
values:
    defaultSettings:
      defaultDataPath: /var/lib/longhorn/
      guaranteedEngineManagerCPU: 12
      guaranteedReplicaManagerCPU: 12
      taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Retain
    csi:
      attacherReplicaCount: 3
      provisionerReplicaCount: 3
      resizerReplicaCount: 3
      snapshotterReplicaCount: 3
    longhornManager:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
    longhornDriver:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule