apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: openwebui
data:
  WEBUI_NAME: "NAI Playground"
  CLUSTER_NAME: "zy-gpu"
  ENABLE_SIGNUP: "true"
  DEFAULT_USER_ROLE: "admin"
  COMMUNITY_HUB_BUNDLE_DOWNLOADS_ENABLED: "1"
  CHAT_RESPONSE_MAX_TOOL_CALL_ITERATIONS: "20"