apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: project-demo
data:
  WEBUI_NAME: "NAI Playground"
  CLUSTER_NAME: "ntnx-nkp"
  STORAGE_DIR: "/app/server/storage"
  ENABLE_SIGNUP: "true"
  DEFAULT_USER_ROLE: "admin"
  COMMUNITY_HUB_BUNDLE_DOWNLOADS_ENABLED: "1"