apiVersion: v1
kind: Service
metadata:
  name: openwebui-svc
  namespace: openwebui
  labels:
    app: openwebui
spec:
  type: ClusterIP
  selector:
    app: openwebui
  ports:
    - name: http
      port: 8080
      targetPort: openwebui
      protocol: TCP