tunnel: zy
credentials-file: /etc/cloudflared/creds/credentials.json

ingress:
  - hostname: jaeger.yolocal.cloud
    service: http://jaeger-jaeger-operator-jaeger-query.istio-system.svc.cluster.local:16686
  - hostname: openwebui.yolocal.cloud
    service: http://openwebui-svc.openwebui.svc.cluster.local:8080
  - hostname: zy-gpu-k8s-mcp.yolocal.cloud
    service: http://kubernetes-mcp-server.kubernetes-mcp-server.svc.cluster.local:8080
  - hostname: longhorn.yolocal.cloud
    service: http://longhorn-frontend.longhorn-system.svc.cluster.local:80
  - hostname: zy-bastion.yolocal.cloud
    service: ssh://171.16.0.9:22
  - hostname: nkplab.yolocal.cloud
    service: http://171.16.0.9:3000
  - hostname: pc.yolocal.cloud
    service: https://171.16.0.10:9440
    originRequest:
      noTLSVerify: true
      originServerName: https://pc.yolocal.cloud
  - hostname: nai.yolocal.cloud
    service: https://171.16.0.66
    originRequest:
      noTLSVerify: true
      originServerName: https://nai.yolocal.cloud
  - service: http_status:404
