apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-mcp-server
  namespace: kubernetes-mcp-server
spec:
  type: oci
  interval: 30m
  url: oci://ghcr.io/containers/charts